services:
  ftp-relay-api:
    platform: linux/amd64
    build: .
    ports:
      - "8000:8000"
    networks:
      - my_network

  sftp-server:
    image: atmoz/sftp
    platform: linux/amd64
    volumes:
      - sftp-data:/home/testuser/upload
    ports:
      - "2222:22"
    command: testuser:testpass:::upload
    networks:
      - my_network

  ftp-server:
    platform: linux/amd64
    image: stilliard/pure-ftpd
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - ftp-data:/home/testuser
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: testuser
      FTP_USER_PASS: testpass
      FTP_USER_HOME: /home/testuser
    networks:
      - my_network

networks:
  my_network:

volumes:
  sftp-data:
  ftp-data:
